### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by snami100** [microsoft/vscode-jupyter-hub#36]
## Environment data

-   VS Code version: 1.83.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1002861100
-   Python Extension version (available under the Extensions sidebar): v2023.10.1002861100
-   OS (Windows | Mac | Linux distro) and version: Windows 10

## Expected behaviour

Should connect to JupyterHub

## Actual behaviour

Doesnt connect, says invalid URL, when using 'Existing JupyterHub Server...'
My URL looks like this:
https://aubf-hig-start.apps.ocp4pbk.kernel.local/user/{username}?token={token}

When im using 'Existing Jupyter Server...' it says, use 'Existings JupyterHub Server...'...

**Comment by DonJayamanne** [comment]
Thanks for filling this issue and sorry you are running into this

Please can you provide a screenshot of the problem
Can you also enable verbose logging for jupyterhub from the settings  and replicate the issue again
Then provide the output from the jupyterhub output panel

**Comment by snami100** [comment]
I don't have the admin rights for this JupyterHub. On older versions i could connect, only on the newer version it was not possible.

**Comment by DonJayamanne** [comment]
Please can you share a screenshot of the problem

**Comment by snami100** [comment]
When using JupyterHub Server
![grafik](https://github.com/microsoft/vscode-jupyter-hub/assets/49515753/c8900ccc-3404-4beb-bcf1-c17eaedcd61a)


When using Jupyter Server
![grafik](https://github.com/microsoft/vscode-jupyter-hub/assets/49515753/f9becbf7-28c8-4702-b2ea-9e550defd799)

**Comment by DonJayamanne** [comment]
Thanks for the screenshots.

The second error is basically a message suggesting you use the new extension
The first error is from the new extension, which is the right appraoch.

* Please could you install the latest pre-release version of the Jupyter and JupyterHub extension.
* Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`
* Similarly please install the latest `Pre-Release` version of the JupyterHub extension

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

How to get to the output?
* Select the command `View: Toggle Output`
* The output panel will appear at the bottom (where terminals are dispaleyd0
* From the dropdown select the `JupyterHub` item
* Copy all of the output and paste it here

Here's a screen sample
![Screenshot 2023-10-13 at 14 27 12](https://github.com/microsoft/vscode-jupyter-hub/assets/1948812/0ac3abed-81f1-4cb5-8cf7-806a7a7c933c)

**Comment by snami100** [comment]
11:44:51.853 [error] Error sending request to https://jhub-highmem-start.apps.ocp4pbk.versatel.local/user/hub/api FetchError: request to https://jhub-highmem-start.apps.ocp4pbk.testment.local/user/hub/api failed, reason: unable to get issuer certificate
    > at ClientRequest.<anonymous> (/home/snami100/.vscode/extensions/ms-toolsai.jupyter-hub-2023.10.1002881100/dist/extension.node.js:63581:18)
    > type = system
    > errno = UNABLE_TO_GET_ISSUER_CERT
    > code = UNABLE_TO_GET_ISSUER_CERT
11:44:52.021 [error] Error sending request to https://jhub-highmem-start.apps.ocp4pbk.testment.local/hub/api FetchError: request to https://jhub-highmem-start.apps.ocp4pbk.testment.local/hub/api failed, reason: unable to get issuer certificate
    > at ClientRequest.<anonymous> (/home/snami100/.vscode/extensions/ms-toolsai.jupyter-hub-2023.10.1002881100/dist/extension.node.js:63581:18)
    > type = system
    > errno = UNABLE_TO_GET_ISSUER_CERT
    > code = UNABLE_TO_GET_ISSUER_CERT
11:44:52.188 [error] Error sending request to https://jhub-highmem-start.apps.ocp4pbk.testment.local/hub/api FetchError: request to https://jhub-highmem-start.apps.ocp4pbk.testment.local/hub/api failed, reason: unable to get issuer certificate
    > at ClientRequest.<anonymous> (/home/snami100/.vscode/extensions/ms-toolsai.jupyter-hub-2023.10.1002881100/dist/extension.node.js:63581:18)
    > type = system
    > errno = UNABLE_TO_GET_ISSUER_CERT
    > code = UNABLE_TO_GET_ISSUER_CERT
11:44:52.189 [error] Failed to determine base url for https://jhub-highmem-start.apps.ocp4pbk.testment.local/user/snur.amin?token=82b7e79f571a456d9f8d5c53715a3af9 Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (/home/snami100/.vscode/extensions/ms-toolsai.jupyter-hub-2023.10.1002881100/dist/extension.node.js:64314:9)

**Comment by DonJayamanne** [comment]
@snami100 Thanks for the logs and the screenshots.
Based on the logs, it seems the certificate is not valid. I.e. the certificate used by the JupyterHub server
Is this some self signed certificate or the like?

I've got a PR that would prompt the user to allow using such un'trusted certificates (but this is not recommended).
However we have run into this in the past where users use self signed certificates, expired certifidates or the like like.

**Comment by DonJayamanne** [comment]
Please can you 
* Download the following file
* Extract it
* Go into VS Code and select `Extensions: Install from VSIX`
* When prompted, please reload VS Code
* Try this new extension and let me know how things go

If it works great, you can keep using this.
I will ship a pre-release version of this extension once its merged into the main branch and will ship a new version in a week or two, along with the latest version of VS Code.
[ms-toolsai-jupyter-hub-insiders.vsix (1).zip](https://github.com/microsoft/vscode-jupyter-hub/files/12973839/ms-toolsai-jupyter-hub-insiders.vsix.1.zip)

**Comment by kalpanachinnappan** [comment]
I am still seeing the "unable to get issuer certificate" error in `v2023.10.1003012305` version of Jupyterhub extension.

**Comment by fecorreiabr** [comment]
I am facing the same issue. My company uses a custom CA to issue certificates, that's the cause of the error. Version `v2023.10.1003012305`.

**Comment by DonJayamanne** [comment]
@fecorreiabr @snami100 @kalpanachinnappan 
* Please can you try installing the latest pre-release version of the extension
* Also, please add the following setting `jupyter.allowUnauthorizedRemoteConnection: true` into VS Code and let me know if this works.
![Screenshot 2023-12-14 at 09 37 02](https://github.com/microsoft/vscode-jupyter-hub/assets/1948812/a89a01d3-4329-4eae-9dd4-9bbe2de043bd)

**Comment by fecorreiabr** [comment]
@DonJayamanne I found out my problem was in the reverse proxy (httpd) config. It needed the `SSLCertificateChainFile` option to force the server to send all the certificate chain in the SSL handshake. This is a node-related problem as described [here](https://github.com/nodejs/node/issues/33705). Now the connection to JupyterHub works as expected.

**Comment by Straboxer** [comment]
@DonJayamanne I have a similar problem, I have the jupyter.allowUnauthorizedRemoteConnection: true and I accept the popus saying it is a self signed certificate, but a Invalid Url always appear.

`10:56:03.239 [error] Error sending request to https://HOSTNAME:9443/hub/api FetchError: request to https://HOSTNAME:9443/hub/api failed, reason: self signed certificate
    > at ClientRequest.<anonymous> 
    > type = system
    > errno = DEPTH_ZERO_SELF_SIGNED_CERT
    > code = DEPTH_ZERO_SELF_SIGNED_CERT
10:56:04.801 [error] Failed to determine base url for https://HOSTNAME:9443/user/jovyan/?token=TOKEN Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl `

**Comment by DonJayamanne** [comment]
@Straboxer are you using vscode.dev or the like (i.e. are you using VS Code from within the browser)?

**Comment by Straboxer** [comment]
Hey @DonJayamanne I am using VS Code native app for Mac M1.

**Comment by DonJayamanne** [comment]
* Please can you enable debug logging using the following setting,
![Screenshot 2024-01-30 at 11 24 26](https://github.com/microsoft/vscode-jupyter-hub/assets/1948812/c28548b5-e1b3-42e3-a84a-355a238801fe)
* Install the following vsix using the command `Install from VSIX`
* When prompted, please reload VS Code 
* Test again and please share the logs from the `JupyterHub` output channel
    * Use the command `Outputs: Show Output Channels` and select `JupyterHub`

**Comment by cchen777** [comment]
Hi @DonJayamanne , thanks for the great extension
I'm facing the same issue to connect to a Jupyterhub URL , i've follow the steps you mentioned
- `jupyter.allowUnauthorizedRemoteConnection: true`
- set Jupyterhub Log level to `debug`
i'm suspecting this is because there's an auth redirect when visit our company's Jupyterhub site but from the logging cannot see any useful information, do you have any suggestion on this? many thanks!
![image](https://github.com/microsoft/vscode-jupyter-hub/assets/56123090/9fb69b89-98ec-461c-b0b4-4ad1b29b96ed)
![image](https://github.com/microsoft/vscode-jupyter-hub/assets/56123090/1e602056-75ca-4476-9b64-6d5357f45d97)

## Environment data
- VS Code Version: 1.86.2
- jupyterhub vscode extension: v2023.10.1003492320 (pre-release)
- jupyter vscode extension: v2024.1.2024012502 (pre-release)
- jupyterhub: 3.1.1
- jupyter-server: 1.24.0

**Comment by DonJayamanne** [comment]
Please open the dev tools using the command `Toggle Developer Tools`
* Then look for errors in the console widow, if there are any, please paste them here
* Also you might want to open the `Network` tab and try again, then all http* requests will be logged along with any errors.
If there are any errors in the network tab as well, please paste them here

**Comment by cchen777** [comment]
Hello @DonJayamanne , 
thanks for your response and sorry for the delay reply, i follow the steps again and sadly there's no console logging or network actively happen from the `Developer Tools` as the screenshot display, I enter multiple times URL and only see the Jupyterhub extension `output` keep printing `Error: Unable to determine base url of Jupyter Hub Server`, i did turn console log level to `Verbose` but still nothing appear there, I wonder if there's a way to show more logging from the jupyterhub vscode extension side for this case

<img width="1789" alt="Screenshot 2024-03-14 at 11 57 00 PM" src="https://github.com/microsoft/vscode-jupyter-hub/assets/56123090/32801e9c-171f-4ff9-8da1-9af43ba4b59b">

**Comment by cchen777** [comment]
> What version of Jupyter Hub is that
we are using `jupyterhub==3.1.1`

> Can you try the url without the trailing ? character
I tried and it didn't help 😞

**Comment by kaigg96** [comment]
Hello @DonJayamanne, I'm facing what seems like the same issue. 

I'm using Docker/Jupyterhub, attempting to connect to the server via my IP address with a SSL. 

Opening the running server in my browser via the address (https://10.XXX.X.XX:8000) redirects me to login as it should, but connecting through VS Code gives an invalid jupyterhub url. 

The log message is the same as well - [error] Failed to determine base url for https://10.XXX.X.XX:8000 Error: Unable to determine base url of Jupyter Hub Server.

It does, however, work when loading through https://localhost:8000 instead of through the IP address. I just need others to be able to connect, hence why I need it to work via my IP address instead.

I've attempted all the troubleshooting you described above, with the same outputs as @cchen777. Any help is appreciated!

VS Code 1.87.2
VS Code extension - Jupyter v2024.2.2024022602 (pre-release)
VS Code extension - Jupyterhub v2023.10.1003492320 (pre-release)
Jupyterhub version 4.1.0

**Comment by lateo-net** [comment]
Same issue : "Invalid JupyterHub URL specified"

VSCode : 1.87.2
Jupyter ext : 2024-02
JupyterHub ext : 2023-10-1003492320 

JupyterHub : 
- 4.0.2 20240401063551, 
- configured with Google OAuth
- nginx reverse proxy
- Valid (let's encrypt) SSL cert and DNS record ; browsers are happy with the setup.

URL in kernel selection : 
https://jupyter.<domain.tld>/user/<someone@gmail.com>/?token=<TokenCreatedFromJupyterHubControlPanel>

-----

For the record I have a working configuration for an air-gapped network (with private CA and different versions of almost everything).

**Comment by DonJayamanne** [comment]
@lateo-net  @cchen777 @snami100 
Please could you
* Download the attached file
* Extract this file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* When prompted to reload VS Code, please do so
* Try to replicate the issue once again
[ms-toolsai-jupyter-hub-insiders.vsix.zip](https://github.com/microsoft/vscode-jupyter-hub/files/14845351/ms-toolsai-jupyter-hub-insiders.vsix.zip)

**Comment by lateo-net** [comment]
@DonJayamanne
Invalid JupyterHub URL specified.

Also tried to uninstall JupyterHub extension then install the insiders vsix and restart VSCode, no luck, same result.

From console dev tools while "create new notebook" : 
```
event.ts:42 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
webviewElement.ts:511 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
index.html?id=8fddd2…tebookRenderer:1021 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
```

No Console event while validating the URL of the JupyterHub server.

**Comment by kaigg96** [comment]
@DonJayamanne 

Here is the jupyterhub output for me:
`08:22:07.069 [error] Error sending request to https://10.XXX.X.XX:8000/hub/api FetchError: request to https://10.XXX.X.XX:8000/hub/api failed, reason: connect ETIMEDOUT 10.XXX.X.XX:8000
    > at ClientRequest.<anonymous> (c:\Users\XXXX\.vscode\extensions\ms-toolsai.jupyter-hub-2024.4.100\dist\extension.node.js:63667:18)
    > type = system
    > errno = ETIMEDOUT
    > code = ETIMEDOUT
08:22:07.073 [error] Failed to determine base url for https://10.XXX.X.XX:8000 Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (c:\Users\XXXX\.vscode\extensions\ms-toolsai.jupyter-hub-2024.4.100\dist\extension.node.js:64409:9)`

**Comment by kaigg96** [comment]
I was able to fix my issue using the following steps:

add env var NODE_TLS_REJECT_UNAUTHORIZED=0
add "http.systemCertificates": true to vs code settings.json
In vs code settings for Jupyter, check "Allow Unauthorized Remote Connection"

Then faced an authentication issue (in spite of using the dummy authenticator). Fixed by having the user log in through the browser. After that, their username/pw combo was accepted by VS code.

**Comment by jamessong** [comment]
Same issue ....

**Comment by jamessong** [comment]
add env var NODE_TLS_REJECT_UNAUTHORIZED=0

Where to set this？command line？

**Comment by jamessong** [comment]
Unable to determine base url of Jupyter Hub Server
> at getJupyterHubBaseUrl
The remote server works well with my desktop version of jupyterlab, so this is vscode or extention issue,  pain in the butt

**Comment by PhenomenaPh** [comment]
Still getting `Unable to determine base url of Jupyter Hub Server` error. Any solution to that problem? Tried every steps from this issue. Nothing seems to be working.

**Comment by hankniel** [comment]
> I was able to fix my issue using the following steps:
> 
> add env var NODE_TLS_REJECT_UNAUTHORIZED=0 add "http.systemCertificates": true to vs code settings.json In vs code settings for Jupyter, check "Allow Unauthorized Remote Connection"
> 
> Then faced an authentication issue (in spite of using the dummy authenticator). Fixed by having the user log in through the browser. After that, their username/pw combo was accepted by VS code.

thank you bro. This solution worked for me

**Comment by anisimov99** [comment]
> In your .bashrc
export NODE_TLS_REJECT_UNAUTHORIZED=0

I'm connecting from a Windows machine. Where am I supposed to find it? Is it ok to create it in a notebook session via `%shell_env NODE_TLS_REJECT_UNAUTHORIZED=0`? Because I've tried it, but it didn't help

**Comment by hankniel** [comment]
> > In your .bashrc
> > export NODE_TLS_REJECT_UNAUTHORIZED=0
> 
> I'm connecting from a Windows machine. Where am I supposed to find it? Is it ok to create it in a notebook session via `%shell_env NODE_TLS_REJECT_UNAUTHORIZED=0`? Because I've tried it, but it didn't help

i think you just set the variable through cmd like set NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by PhenomenaPh** [comment]
Any progress on this issue? I can easily connect via pycharm jupyter connection but cant do the same with vscode. I get only 
`Error: Unable to determine base url of Jupyter Hub Server`

**Comment by DonJayamanne** [comment]
Please can you
* Uninstall JupyterHub extension
* Download the attached file
* Extract this file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* Enable logging (debug logging)
* When prompted to reload VS Code, please do so
* Try to replicate the issue once again
* Capture all the logs from the `JupyterHub` output panel
* Share the logs



[ms-toolsai-jupyter-hub-insiders.vsix.zip](https://github.com/user-attachments/files/16423209/ms-toolsai-jupyter-hub-insiders.vsix.zip)


Screenshot for enabling logging


![Image](https://github.com/user-attachments/assets/f6515fff-304f-4eff-bc88-139f9f2ce4b2)


To get to the logs, please open the bottom output panel (use the command `Outupt: Focus Output View`)
& then select `JupyterHub`


![Image](https://github.com/user-attachments/assets/309a13d9-14ea-4e70-b617-4385556e1064)

**Comment by PhenomenaPh** [comment]
@DonJayamanne 

Ive done every step from your instruction. Here is the output:
`[error] Failed to determine base url for {my hub url}: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (/Users/rustemhutiev/.vscode/extensions/ms-toolsai.jupyter-hub-2024.5.100/dist/extension.node.js:64986:9)`
    
I have tried several urls:
- {jupyter_url}/user/{user_name}/lab
- [https://jupyter.{domain.tld}/user/{someone@gmail.com}/?token={TokenCreatedFromJupyterHubControlPanel}]

<img width="669" alt="image" src="https://github.com/user-attachments/assets/7fcf86e6-db9b-4dc6-9a7e-c709120307e5">

**Comment by DonJayamanne** [comment]
1. When entering the url , you do not need to include the username, etc/
Just `jupyter_url (https://jupyter.{domain.tld})` is sufficient (exclude the trailing `/user/{user_name}/lab`)

2. Also, can you try entering the following url in the browser and let me know what you get `https://jupyter.{domain.tld}/hub/api`

Let me know if that works, and I'll try to update the code to try and strip that out.

**Comment by PhenomenaPh** [comment]
Hello! @DonJayamanne 

Thank you for your fast feedback. When i type https://jupyter.{domain.tld}/hub/api i get `{"version": "4.1.5"}`
As for (https://jupyter.{domain.tld}) i still get a basic error without any other logs: `Error: Unable to determine base url of Jupyter Hub Server > at getJupyterHubBaseUrl (/Users/xxx/.vscode/extensions/ms-toolsai.jupyter-hub 2024.5.100/dist/extension.node.js:64986:9)`

What else can i provide in order to give you full details on this issue

**Comment by PhenomenaPh** [comment]
For context: my URL is not starting with https://jupyter.{domain.tld}/... but rather https://ml-jupyterhub.{domain.tld}/
The subdomain in my case is 'ml-jupyterhub' instead of just 'jupyter'. This could be due to a specific configuration for a machine learning-focused JupyterHub instance in my organization. And if it is relevant, I think that it is configured via k8s.

**Comment by AsyqD** [comment]
> I was able to fix my issue using the following steps:
> 
> add env var NODE_TLS_REJECT_UNAUTHORIZED=0 add "http.systemCertificates": true to vs code settings.json In vs code settings for Jupyter, check "Allow Unauthorized Remote Connection"
> 
> Then faced an authentication issue (in spite of using the dummy authenticator). Fixed by having the user log in through the browser. After that, their username/pw combo was accepted by VS code.

Thank U so much!

**Comment by XinSong** [comment]
I have the same problem, but the solution above doesn't work for me

**Comment by gothma** [comment]
I've also came across this, but got the additional error message (domain anonymized):
```
16:32:09.631 [error] Error sending request to https://***/hub/api FetchError: request to https://***/hub/api failed, reason: getaddrinfo ENOTFOUND ***
```

After playing around I've noticed that the plugin does not seem to respect proxy environment variables. In my setup I'm behind an http proxy and the specific jupyterhub url can only be resolved by the proxy, not my own client.

Is this correct? Is there any proxy support coming?

**Comment by Jonnokc** [comment]
Same problem here with certificate error.
