### ISSUE TITLE
Using an email address as a username fails to get a list of kernels

### ISSUE THREAD

**Issue by mastercard-rob** [microsoft/vscode-jupyter-hub#41]
I have JupyterHub integrated with azuread and using email address as the username. The '@' is getting encoded and the call to /api/kernels is failing with a 404.

**Comment by DonJayamanne** [comment]
Sorry you are running into this Odis

Please can you try installing the latest pre-release version of the Jupyter hub extension
This was fixed in the pre release version

**Comment by marcelgs** [comment]
@mastercard-rob
I had to install the pre-release version (v2023.10.1003011100) of the Jupyter extension as well in order to get this to work.

**Comment by DonJayamanne** [comment]
Thanks closing as fixed

**Comment by dschach99** [comment]
I am currently running into a similar problem when using a username including brackets and whitespaces. The brackets '(' and ')' are getting encoded and the call also fails with a 404. Also, using the current pre-release version (v2023.10.1003492320) did not fix it.

**Comment by quantum-byte** [comment]
> I am currently running into a similar problem when using a username including brackets and whitespaces. The brackets '(' and ')' are getting encoded and the call also fails with a 404. Also, using the current pre-release version (v2023.10.1003492320) did not fix it.

This is pretty sure not an issue in `vscode-jupyter-hub` but rather the `vscode-jupyter` extension. Please see https://github.com/microsoft/vscode-jupyter/issues/15439
